# swap
vm.swappiness=200
vm.watermark_boost_factor=15000
vm.watermark_scale_factor=3000
vm.page-cluster = 0
vm.compaction_proactiveness = 100

vm.vfs_cache_pressure = 50
# hugepage
vm.nr_overcommit_hugepages=1024
vm.khugepaged.pages_to_scan = 8192
vm.khugepaged.scan_sleep_ms = 1000
vm.khugepaged.max_ptes_none = 511


# KSM
#
# Allow KSM to share a single page across many processes (Aggressive)
vm.ksm_max_page_sharing = 1024

# The sleep time between scans in milliseconds (Aggressive)
# Lower = faster deduplication but more background CPU usage
vm.ksm_sleep_millisecs = 20
